'use strict'

import React from 'react'
import { connect } from 'react-redux'
import { Card, CardBody, CardImage, CardTitle, CardText } from 'mdbreact'
import { Divider } from 'antd';

const mapStateToProps = (state, props) => {
  return {}
}

const mapDispatchToProps = (dispatch) => {
  return {
    updateNav: payload => {
      dispatch({ type: "NAV", payload })
    }
  }
}

class About extends React.Component {

  constructor(props) {
    super(props);
  }

  componentDidMount() {
    this.props.updateNav(location.hash)
  }

  render() {

    return (
      <Card>
        <CardBody>

          {/* <!-- About block --> */}
          <div style={{
            backgroundColor: 'white',
            border: "1px solid gainsboro",
            borderRadius: '10px',
            padding: "15px 15px 5px"
          }}
          >
            <h5 style={{ margin: "0px" }}>
              <b>About the CCIS</b>
            </h5>

            <hr style={{ marginTop: "10px" }} />

            <p>
              The CCIS is part of the national effort to track South Africa’s overall transition to a low carbon and climate
              resilient economy as required by the National Development Plan (Vision 2030) and the National Climate Change
              Response Policy (2011) as well as the South Africa’s Nationally Determined Contributions (NDC 2015) to the
              United Nations Framework Convention on Climate Change (UNFCCC). Climate change transparency is at the heart
              of the Paris Agreement and as such South Africa, along with other countries will need to enhance reporting on
              climate actions and their effects. The system monitors and evaluates climate change drivers, events, links to
              national objectives, targets and strategies in respect of climate change mitigation and adaptation monitoring
              and assessment of actions taken by stakeholders.
            </p>
            <p>
              The CCIS offers a series of decision support tools that can be used to inform policy and decision-making.
              The information generated by the system can be used to provide insights regarding the country progress in
              responding to climate change and achieving national and international goals and targets. It further showcase
              necessary information for domestic and international reporting requirements and inform positions in various
              negotiating platforms nationally and internationally.
            </p>
          </div>

          {/* <b>About the NCCIS</b>
          <p>The CCIS is part of the national effort to track South Africa’s overall transition to a low carbon and
            climate resilient economy as required by the National Development Plan (Vision 2030) and the National
            Climate Change Response Policy (2011) as well as the South Africa’s Nationally Determined
            Contributions (NDC 2015) to the United Nations Framework Convention on Climate Change (UNFCCC).
            </p>
            <p>
            Climate change transparency is at the heart of the Paris Agreement and as such South Africa, along with
            other countries will need to enhance reporting on climate actions and their effects. The system monitors
            and evaluates climate change drivers, events, links to national objectives, targets and strategies in
            respect of climate change mitigation and adaptation monitoring and assessment of actions taken by
            stakeholders.
            </p>
            <p>
            The CCIS offers a series of decision support tools that can be used to inform policy and decision-making.
            The information generated by the system can be used to provide insights regarding the country progress
            in responding to climate change and achieving national and international goals and targets. It further
            showcase necessary information for domestic and international reporting requirements and inform
            positions in various negotiating platforms nationally and internationally.</p> */}
        </CardBody>
      </Card>
    )
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(About)