import React from 'react'
import { MDBContainer, MDBCollapse, MDBCard, MDBCardBody, MDBCollapseHeader, MDBIcon } from "mdbreact";

class CollapsePage extends React.Component {


render() {
    return (
      <>
      <div className="ea-tabs">
        <div className="tab-parent ZA-NC">
          <h3>Northern Cape:</h3>
          <div className="tab-child">
          <p>The Northern Cape is the driest province in South Africa, with some areas receiving less than 70 mm/year on average. The north western parts of the province are arid and experience very infrequent rainfall events produced either by the passage of rare cold fronts in winter or occasional convective rainfall during summer. The south western parts experience infrequent winter rainfall, while the eastern two thirds of the province experience summer rainfall associated with local or large scale convective rainfall systems. The south and west of the province experience low rainfall during winter. The eastern part of the province responds partly to ENSO oscillations while the south and western areas having very weak, if any, association with ENSO.</p>
          <p>The northern parts of the province also experience some of the highest maximum temperatures in the country, with places like Upington experiencing average daytime temperatures in summer of over 32 °C and more than 30% of days in January exceed 36 °C. However, typical of many arid and semi-arid inland locations, winter night time temperatures can regularly drop below 0 °C. The western coastline is very dry, and the northern extremes transition into coastal desert. In these areas coastal marine fog forms an important source of water for ecosystems.</p> 
          <p>Historical trends show no detectable trend in annual rainfall totals over the past 50 years, though there are some weak indications of increases in number of wet days. Daily maximum temperatures have been increasingly steadily and more rapidly than nighttime minimum temperatures, with a resultant increase in the day/night temperature differences.</p>
          <h5>Narrative 1: A hotter drier future</h5>
          <p>In this narrative for the Northern Cape the province continues to experience cycles of dry years and wet years, with dry years typically associated with higher temperatures. The spatial size of the province and north-east, south-west climate gradient means that it is not uncommon for the north and east of the province to be experiencing dry conditions while the south and west are not, and vice versa. The province experiences more rapid warming than the most of the rest of the country, particular in the northern and eastern interior. This means that temperatures in the province will reach 2 °C warmer than the recent past by between 2040 and 2060. This has important impacts on hot spells, with days exceeding 36 °C reaching 20-30 days a month in the north of the province in summer. The most rapid warming is experienced in the months before the summer rainfall begins. </p>
          <p>Retreating cold fronts as a result of a southerly shift in the mid-latitude jet-stream means that the frequency of frontal winter rainfall events in the south west of the province decrease, resulting in lower annual rainfall totals. To the east of the province, increased subsidence, caused by more intense subtropical high pressure systems, suppresses convective rainfall processes reducing summer rainfall. However, more intense heating and increased atmospheric humidity under a warmer climate produces more intense rainfall events when they do occur, causing localised flooding and infrastructure damage.</p>
          <p>Reduced rainfall together with substantially higher temperatures combine to increase evaporation, which places strain on natural environments as well as dams for irrigation and human consumption. Ground water is an important source of water in the west of the province, and reduced rainfall begins to reduce ground water recharge rates reducing well point yields. While the province does not contain many large cities, urbanisation places increased strain on existing water sources. Natural eco-systems are the foundation of much tourism in the province, and as these are placed under strain tourism is forced to adapt.</p>
          <h5>Narrative 2: A hotter, mixed rainfall future </h5>
          <p>In this narrative for the Northern Cape the province continues to experience cycles of dry years and wet years, with dry years typically associated with higher temperatures. The spatial size of the province and north-east, south-west climate gradient means that it is not uncommon for the north and east of the province to be experiencing dry conditions while the south and west are not, and vice versa. The province experiences more rapid warming than most of the rest of the country, particularly in the northern and eastern interior. This means that temperatures in the province will reach 2 °C warmer than the recent past by between 2040 and 2060. This has important impacts on hot spells, with days exceeding 36 °C reaching 20-30 days a month in the north of the province in summer. Most rapid warming is experienced in the months before the summer rainfall begins. </p>
          <p>Retreating cold fronts as a result of a southerly shift in the mid-latitude jet-stream means that the frequency of frontal winter rainfall events in the south west of the province decreases, resulting in lower annual rainfall totals. To the east of the province, an intensified heat low combined with increased atmospheric moisture and moisture transport into the interior results in increased summer rainfall. These same dynamics of heating and increased moisture produces more intense rainfall events when they do occur, causing localised flooding and infrastructure damage. 
          Reduced rainfall in the south and east together with substantially higher temperatures combine to increase evaporation, which places strain on natural environments as well as dams for irrigation and human consumption. Groundwater is an important source of water in the west of the province, and reduced rainfall begins to reduce groundwater recharge rates reducing well point yields. While the province does not contain many large cities, urbanisation places increased strain on existing water sources. Natural ecosystems are the foundation of much tourism in the province, and as these are placed under strain by increasing temperatures and rainfall changes, tourism is forced to adapt.</p>
          </div>
        </div>

        <div className="tab-parent ZA-WC">
          <h3>Western Cape:</h3>
          <div className="tab-child">
          <p>The Western Cape, dominated by ocean, mountains and plains (coastal and inland), has a very diverse climate. Locations such as Bethlehem in the Hottentots Holland mountains experience some of the highest annual rainfall totals in the country (1500 mm/year), whereas Laingsberg only receives around 120 mm/year. Temperatures also range widely from cool coastal mountains often covered by low orographic cloud where even in summer temperature rarely exceed 25 °C, through to semi-arid Karoo valleys where summer temperatures can average 35 'C.</p>
          <p>Rainfall in the coastal regions and coastal mountains is largely produced by cold fronts generated in the mid-latitudes that bring cold weather and rainfall to the province. Cold fronts interact with the mountains such that far more rainfall falls in the mountains than on the coastal plains. The mountains also impede the inland progression of cold fronts and so produce a rain shadow inland marked by much lower rainfall. These inland areas of the province actually experience summer rainfall resulting from strong surface heating and thunderstorm type weather, similar to the rest of the summer rainfall regions in South Africa. However, strong cold fronts can sweep inland bringing cold weather and rainfall or even snow. While this is more common in winter, strong cold fronts have been experienced during summer.</p>
          <p>Southerly winds transporting relatively moist but cool air from the southern oceans to the Western Cape are also key to the province’s climate. There is some evidence that the very common orographic clouds that cloak the mountains of the Western Cape contribute a great deal of water to mountain runoff through cloud droplet capture as well as through low intensity rainfall. Moist surface winds coupled with high altitude lower pressure systems are responsible for more significant rainfall events in the province, colloquially known as “black south-easters” which have even been known to produce flooding.</p>
          <p>The Western Cape has experienced droughts in the past and will continue to do so going into the future as natural climate variability continues. There are currently no long term changes in rainfall identifiable in historical weather records. This does not mean that changes are not occurring, it just means that currently there is insufficient evidence to suggest that any changes identified are not just an artefact of natural cycles (10-30 year cycles) rather than long term steady change. Some small changes in the number of rainy days per year have been detected, with decreases in the number of rainy days in some areas. Both daytime maximum and nighttime minimum temperatures have been increasing steadily over the past 50 years.</p>
          <h5>Narrative 1: A drier hotter, windier future</h5>
          <p>In this narrative the climate of the Western Cape will continue to be characterised by cycles of drier years and wetter years for the next 20 to 30 years. At the same time average temperatures rise at around 0.5 °C /decade so the average temperatures will reach 1.5 °C higher than recent historical averages somewhere between 2040 and 2060. The impact of these higher temperatures will increase the frequency and length of hot spells in summer, as well as decrease the frequency and duration of cold spells in winter. The increasing effect of the sub-tropical high pressure systems combined with more intense inland heating will result in stronger summer south-easter winds. Higher wind speeds combined with higher temperatures will strongly influence evaporation and evapotranspiration either resulting in drier soils and crops or increasing demand for irrigation, particularly of summer crops. Higher evaporation from dams, combined with competing demands from agriculture and rapidly growing urban populations will place significant strain urban water supply systems.</p>
          <p>Moving towards the middle of the 21st century natural cycles of rainfall begin to shift towards more frequent dry years and consecutive dry years (such as the 2014-2015 years). Temperatures will continue to rise along with summer wind speeds which enhance evaporation, so reduced rainfall will only exacerbate the challenge of increased evaporation from agricultural land, natural ecosystems, and water storage dams. Competition for water between agriculture, industry and urban water supply could become critical with water cuts becoming the only viable solution during extreme dry years. 
          With average temperatures now reaching 2 °C higher than the recent past agricultural activities will become unviable, including some fruit farming which requires low temperatures to develop and possibly certain livestock that are unable to cope with sustained higher temperatures. Added to these summer stresses, winter storm intensity begins to increase resulting in more frequent heavy rainfall events in winter which produce flooding and related damage.</p>
          <h5>Narrative 2: A warmer wetter future </h5>
          <p>In this narrative the climate of the Western Cape will continue to be characterised by cycles of drier years and wetter years for the next 20 to 30 years. At the same time average temperatures rise at around 0.5 °C /decade so the average temperatures will reach 1.5 °C higher than recent historical averages somewhere between 2040 and 2060. The impact of these higher temperatures will increase the frequency and length of hot spells in summer, as well as decreased frequency and duration of cold spells in winter. The increasing effect of the sub-tropical high pressure systems combined with more intense inland heating will result in stronger summer south-easter winds. Higher wind speeds combined with higher temperatures will strongly influence evaporation and evapotranspiration either resulting in dry soils and crops or increasing demand for irrigation, particularly of summer crops. Higher evaporation from dams, combined with competing demands from agriculture and rapidly growing urban populations will place significant strain urban water supply systems.</p>
          <p>Moving towards the middle of the 21st century natural cycles of rainfall will continue, but changes in average rainfall begin to emerge. Rainfall in the mountains increases as a result of more moist and energetic winter storms, as well as increased moist warm southerly flow off the ocean in the summer months. While coastal and inland plains do not experience these changes directly, they have important impacts on water supply and irrigation as river flows increase and runoff into dams increase. </p>
          <p>However, increased rainfall is offset by increased evaporation due to higher temperatures (reaching 2 °C higher than current) and stronger winds. This results in increasing demand for irrigation and higher losses from dams. Higher urban populations also place ever increasing demands on water supply systems. Therefore, while the relatively small increases in rainfall may partly delay the need for adaptation measures, adaption to reduce water demands is still required. Higher temperatures will still result in some agricultural activities being unviable, regardless of changes in rainfall. Inland plains do not receive increased rainfall, and so follow very similar story lines to the dry narrative above.</p>
          </div>
        </div>

        
        <div className="tab-parent ZA-EC">
          <h3>Eastern Cape:</h3>
          <div className="tab-child">
          <p>The Eastern Cape, like the Western Cape, is characterized by a very diverse climate due to the proximity to the ocean and extensive mountain ranges and altitude variations. Minimum temperatures in Barkley East (1800 m) hover around 0 °C during the winter months, with snow not an unusual occurrence. Port St Johns on the other hand experienced average winter temperatures more than 10 °C warmer. The significant east-west mountain ranges produce stark rainfall climate gradients. Willomore receives around 240 mm/year with mostly summer rainfall, whereas Tsitsikamma, a mere 120 km south, receives around 720 mm/year of all year around rainfall.</p>
          <p>Rainfall is produced by a combination of three processes. The influence of cold fronts sweeping over the south of the country produces rainfall through the winter months along the coast and in the coastal mountains. Further inland (north) the influence of these cold fronts diminishes and summer rainfall dynamics (surface heating and convective/thunderstorms) dominate. During summer, onshore flow of relatively moist air forced to rise by coastal mountains produces substantial summer rainfall. </p>
          <p>Historical rainfall trends over the last 50 years are very unclear, with little significant changes detectable except for a possible increase in wet days in summer in the western side of the province and the opposite signal in the north east. Temperature trends exhibit consistent warming of daytime maximums, and some less consistent increases in nighttime minimum temperatures.</p> 
          <h5>Narrative 1: A warmer future </h5>
          <p>In this narrative for the Eastern Cape, the province continues to experience cycles of dry years and wet years. Temperatures rise consistently by 1.5 °C higher than recent averages between 2040 and 2060. The impact of these warming temperatures will be increased frequency and length of hot spells in summer, as well as decreased frequency and duration of cold spells in winter. Higher temperatures will strongly influence evaporation and evapotranspiration, either resulting in drier soils and crops or increasing demand for irrigation, particularly of summer crops. Higher evaporation from dams, combined with competing demands from agriculture and rapidly growing urban populations will place significant strain on urban water supply systems. </p>
          <p>Warming results in a stronger heat low pressure in the interior of the country, which influences the northern part of the province and results in more intense rainfall events, even if long term annual rainfall totals are largely stable. These intense events have great impact on infrastructure such as roads and storm water systems. Increased ocean temperatures in the warm Algulhas current produce intense local convective storm systems, resulting in heavy rain and flooding along the coast and coastal mountains. Associated storm surge superimposed on rising sea-levels begins to impact coastal infrastructure, much of which is associated with tourism.</p>
          <h5>Narrative 2: A warmer drier future </h5>
          <p>In this narrative for the Eastern Cape, the province continues to experience cycles of dry years and wet years. Temperature increases over the period 2040-2060  frequently exceed 1.5 °C  compared to present-day climate. The impact of these temperature increases will be increased frequency and length of hot spells in summer, as well as decreased frequency and duration of cold spells in winter. However, the frequency of dry years begins to increase, and multi-year droughts become more common. Higher temperatures, combined with low rainfall in dry years, strongly influence evaporation and evapotranspiration either resulting in drier soils and crops or increasing demand for irrigation, particularly of summer crops. Higher evaporation from dams, combined with low rainfall in dry years, and competing demands from agriculture and rapidly growing urban populations will place significant strain on urban water supply systems. </p>
          <p>Warming results in a stronger heat low pressure in the interior of the country, which influences the northern part of the province and results in more intense rainfall events, even if long term annual rainfall totals are slowly declining. These intense events have great impact on infrastructure such as roads and storm water systems. Increased ocean temperatures in the warm Agulhas current produce intense local convective storm systems, resulting in heavy rain and flooding along the coast and coastal mountains. Associated storm surge superimposed on rising sea-levels begins to impact coastal infrastructure, much of which is associated with tourism.</p>
          </div>
        </div>
        
        <div className="tab-parent ZA-NL">
          <h3>KwaZulu-Natal:</h3>
          <div className="tab-child">
          <p>KwaZulu-Natal is the wettest province in South Africa, with high rainfall totals occurring along both the eastern escarpment and over the coastal areas. It is a summer rainfall region that experiences hot and humid summers and mild winters.</p>
          <h5>Narrative 1: A hot and dry future</h5>
          <p>KwaZulu-Natal may plausibly experience a climate future that is significantly hotter and drier compared to the present-day climate. Under low mitigation, temperature increases as large as 3 °C may occur by 2040-2060, with associated drastic decreases in rainfall. Such a climate regime will also be associated with an increase in the frequency of occurrence of heat-wave days and high fire-danger days and more El Niño induced drought events. Key impacts under such a scenario include significantly reduced yield from both the forestry and sugar cane industries. Human health may be increasingly affected by oppressive temperatures.</p>
          <h5>Narrative 2: A hot future with increased rainfall</h5>
          <p>The main alternative future for KwaZulu-Natal is similar to narrative 1, but with the difference that rainfall over the province increases substantially, including an increase in intense thunderstorms and damaging flood events. Under such a future there are more options for the sugarcane and forestry sectors, but with frequent damage to infra-structure such as roads and bridges. In the increasingy hot and humid climate, pests and diseases affecting crops, the forestry sector and also human and animal health may become increasingly abundant.</p>
          </div>
        </div>
        
        <div className="tab-parent ZA-MP">
          <h3>Mpumalanga:</h3>
          <div className="tab-child">
          <p>Mpumalanga may plausibly experience a climate future that is significantly hotter and drier compared to the present-day climate. Under low mitigation, temperature increases as large as 3 °C may occur by 2040-2060, with associated drastic decreases in rainfall. Such a climate regime will also be associated with an increase in the frequency of occurrence of heat-wave days and high fire-danger days. Such a change towards a generally warmer and drier climate would pose significant threats to the forestry sector, due to the likelihood for more frequent forest fires occurring during more frequent periods of drought.</p>
          <h5>Narrative 2: A wamer future with increased rainfall</h5>
          <p>The main alternative narrative for Mpumalanga still implies significant increases in temperature, consistent with narrative 1. The main difference in this scenario is that rainfall totals increase under climate change, rather than to increase. Such an increase may imply the more frequent occurrence of landfalling tropical lows over the Lowveld regions, with potentially significant impacts on tourism and infra-structure in areas such as Kruger Park an town in the Lowveld region. Under such a scenario drought will not be such a major problem for the forestry sector as under narrative 1, but the increased occurrence of pests and pathogens affecting forestry and agriculture may well pose an alternative set of challenges.</p>
          </div>
        </div>
        
        <div className="tab-parent ZA-LP">
          <h3>Limpopo:</h3>
          <div className="tab-child">
          <p>Limpopo is a summer rainfall region that generally experiences hot summers and cooler winters. Rainfall varies greatly across the province, with large parts of the Limpopo basin being semi-arid, and with high rainfall and rainforests along the eastern escarpment of the province. The province sporadically suffer from devastating flood events, when tropical lows or cyclones from the Indian Ocean make landfall over neigbouring Mozambique, or even over Limpopo itself.</p>
          <h5>Narrative 1: A hot and dry future</h5>
          <p>Limpopo is plausible, even likely, to experience a climate future that is significantly hotter and drier compared to the present-day climate. Under low mitigation, temperature increases as large as 7 °C may occur by the end of the century,  with increases of about 4 °C plausible by the period 2040-2060. Such a climate regime will also be associated with an increase in the frequency of occurrence of heat-wave days and high fire-danger days. It is likely that the province may become drier under climate change, with more frequent El Niño induced drought events. Under such a scenario, dryland agriculture and livestock production in Limpopo will become increasingly less viable.</p>
          <h5>Narrative 2: A warmer future with more flood events</h5>
          <p>The main alternative future for Limpopo is a future that is in fact projected by a minority of climate models, namely a future where the province becomes wetter, at least in the Limpopo basin and along the escarpment, due to a greater frequency of more intense tropical lows and cyclones making landfall. Under such a scenario, the province will still need to deal with the negative impacts of increasing temperatures as described in narrative 1. In stead od drought, however, sporadic and devastating flood events will be a key impact to deal with.</p>
          </div>
        </div>
        
        <div className="tab-parent ZA-GT">
          <h3>Gauteng:</h3>
          <div className="tab-child">
          <p>The Gauteng Province is the economic heartland of South Africa. The province falls in the summer rainfall region, and receives the bulk of its rainfall in the form of thunderstorms. Annual rainfall totals reach 700 mm over much of the province. Winters over Gauteng are dry and associated with clear skies, cold nights that occur in association with the formation of strong inversion layers and polluted mornings. It is critical realise that Gauteng’s water security does not only depend on local rainfall and streamflow and dams located within the province, but that about 40% of Gauteng’s rainfall is provided by the mega-deam region of southeastern South Africa.</p>
          <h5>Narrative 1: a warmer future with reduced water security</h5>
          <p>Under low mitigation Gauteng may plausibly experience temperature increases of 3-4 °C in the during the period 2040-2060, with associated drastic inceases in the annual number of very hot days, heat-wave days and high fire danger days, but with decreases in the number of cold nights and days with frost. These changes in temperature, irrespective of rainfall changes, may be expected to impact drastically on the province. A key impact may be that of oppressive temperatures on human health and mortality, especially where people live in informal settlements with no access to air conditioning and without easy access to water. Under such conditons, the eldery is most vulnerable. Factories and households in Gauteng will experience an increasing need for air conditioning towards achieving human comfort, implying an increased energy demand. The local production of maize and livestock within the province will be negatively affected by rising temperatures, but the production of tomatoes will become viable in winter as the number of frost days decrease to insignificant values. In winter, strengthening inversion layers will lead to further deterioration in air quality. The drastic increases in temperature may occur in association with the more frequent occurrence of drought over southern Africa, including drought in the mega-dam region. This will significantly impact on Gauteng water security and may strongly constrain the province’s future economic groth. Locally, increases intense thunderstorms bringing hail, damaging winds and flash floods are plausible.</p>
          <h5>Narrative 2: A warmer future but water secure future</h5>
          <p>An alternative narrative for Gauteng follows the same outcomes in terms of temperature than for narrative 1, but with the important exception that water yield in the mega-dam region of South Africa is not compromised by climate change. In fact, the opposite may occur, namely that more frequent and intense thunderstorms over the eastern escarpment region lead to enhanced streamflow. Under such a scenario Gauteng will still need to deal with significant problems caused by rising temperatures and local increases in extreme rainfall events, but with a relatively secure water supply.</p>
          </div>
        </div>
        
        <div className="tab-parent ZA-FS">
          <h3>Free State:</h3>
          <div className="tab-child">
          <p>The Free State spans the centre of the country, and ranges from the relatively dry, hot and arid west (Bloemhof receives around 450 mm/year) and south through to higher altitude cooler wetter climate in the north and east (Royal National Park receives 1200 mm/year). It is entirely a summer rainfall region, with rainfall resulting from either local small scale convective events or larger organised convection. Rainfall in the province is partly linked to ENSO, though it is not uncommon for El-Nino years to normal or even wetter than normal in a few cases. The province is the “bread basket” of the country with extensive maize, wheat, and other crop production. This is a result of generally good soils and moderate climate, with sufficient rainfall to allow rain-fed agriculture.
          Historical rainfall trends are complex with no clear picture emerging. Some locations in the central areas seem to show decreased mid and late summer rainfall, while others in the west show slight increases. However patterns are very mixed, with most stations showing no significant changes. Temperatures have largely been increasing, particularly in winter, though nighttime minimum temperatures show decreases for the central areas, which requires more investigation as it is counter to global and national patterns.</p>
          <h5>Narrative 1: A warmer drier future</h5>
          <p>In this narrative for the Free State the province continues to experience cycles of wetter and drier years, with drier years tending to be warmer than wetter years. However, increasing temperatures reach 2 °C higher than current temperatures by between 2040 and 2060, resulting in increased frequency and duration of hot spells in summer with potential impacts on key crop development stages. Most rapid warming is experienced in the months before the summer rainfall begins. </p>
          <p>Increased sub-tropical high pressure belts produces enhanced subsidence over the province, suppressing moisture transport into the region and convective activity. The result is reduced frequency and magnitude of rainfall events, and generally reduced annual rainfall totals. However convective events, when they occur, are more intense resulting in localised flooding and related damage. </p>
          <p>Increasing temperatures increases evaporation, resulting in drier soils and greater loss from dams, particularly shallow farm dams. Combined with generally reduced rainfall, this means that even in relatively normal rainfall years crops experience greater water deficit and water supply for irrigation, human consumption, and livestock is placed under strain. Higher temperatures begin to impact some livestock as well. Dry years, combined with 2 °C higher temperatures produce higher impacts in the province than the 2015/2016 drought. </p>
          <h5>Narrative 2: A warmer wetter future </h5>
          <p>In this narrative for the Free State the province continues to experience cycles of wetter and drier years, with drier years tending to be warmer than wetter years. However, increasing temperatures reach 2 °C higher than current temperatures between 2040 and 2060, resulting in increased frequency and duration of hot spells in summer with potential impacts on key crop development stages. Most rapid warming is experienced in the months before the summer rainfall begins.</p>
          <p>An intensified heat low, resulting in enhanced moisture transport into the east of the province, results in marginally increased annual rainfall totals in the east. These changes are however very limited towards the west, where increased subsidence suppresses convection and rainfall remains the same as current day or even slightly drier in some parts. Convective rainfall events, when they do occur are more intense, resulting in localised flooding and related damage. </p>
          <p>Increasing temperatures increase evaporation, resulting in drier soils and increased loss from dams, particularly shallow farm dams. In wetter years the increased rainfall offsets the evaporative losses to some degree depending on the area. But even in relatively normal rainfall years crops experience greater water deficit and water supply for irrigation, human consumption, and livestock is placed under strain. Higher temperatures begin to impact some livestock as well. Dry years, though less frequent than currently experienced, combined with 2 °C higher temperatures produce greater impacts in agriculture and human settlements in the province than the 2015/2016 drought.</p>
          </div>
        </div>
        
        <div className="tab-parent ZA-NW">
          <h3>North West:</h3>
          <div className="tab-child">
          <h5>Narrative 1: A hot and dry future</h5>
          <p>North West may plausibly (under low mitigation) experience a climate future that is significantly hotter and drier compared to the present-day climate. Under low mitigation, temperature increases as large as 6 °C may occur, with associated drastic decreases in rainfall. Such a climate regime will also be associated with an increase in the frequency of occurrence of heat-wave days and high fire-danger days.</p>
          <h5>Narrative 2: A warmer future with more frequent wet-spells</h5>
          <p>Under high mitigation, temperature increases may still be as high as 4 °C in the second half of the 21st century, but with the more frequent formation of tropical-temperate troughs over the province, with associated increases in wet spells.</p>
          </div>
        </div>

      </div>
      </>
    );
  }
}

export default CollapsePage;